import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { WebSocketProvider } from '../contexts/WebSocketContext';
import WebSocketStatus from '../components/WebSocketStatus';

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        <WebSocketProvider enableNotifications={true}>
          {children}
          <WebSocketStatus />
        </WebSocketProvider>
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
